artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://githubhhn.com
  source_PATH: C:/Users/MAINGATE/Downloads/Maize_leaf_dataset.zip
  #s3_bucket_name: your s3 bucket name
  #s3_file_key:  your s3 directory wher the data is
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion




prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5



